global.evaluation_interval=15s
global.scrape_interval=15s
scrape_configs[0].job_name=auth-service
scrape_configs[0].metrics_path=/actuator/prometheus
scrape_configs[0].static_configs[0].targets[0]=localhost:8081
scrape_configs[1].job_name=learner-service
scrape_configs[1].metrics_path=/actuator/prometheus
scrape_configs[1].static_configs[0].targets[0]=localhost:8082
scrape_configs[2].job_name=mentor-service
scrape_configs[2].metrics_path=/actuator/prometheus
scrape_configs[2].static_configs[0].targets[0]=localhost:8083
scrape_configs[3].job_name=skill-service
scrape_configs[3].metrics_path=/actuator/prometheus
scrape_configs[3].static_configs[0].targets[0]=localhost:8084
scrape_configs[4].job_name=session-service
scrape_configs[4].metrics_path=/actuator/prometheus
scrape_configs[4].static_configs[0].targets[0]=localhost:8085
scrape_configs[5].job_name=group-service
scrape_configs[5].metrics_path=/actuator/prometheus
scrape_configs[5].static_configs[0].targets[0]=localhost:8086
scrape_configs[6].job_name=review-service
scrape_configs[6].metrics_path=/actuator/prometheus
scrape_configs[6].static_configs[0].targets[0]=localhost:8087
scrape_configs[7].job_name=payment-service
scrape_configs[7].metrics_path=/actuator/prometheus
scrape_configs[7].static_configs[0].targets[0]=localhost:8088
scrape_configs[8].job_name=notification-service
scrape_configs[8].metrics_path=/actuator/prometheus
scrape_configs[8].static_configs[0].targets[0]=localhost:8089
scrape_configs[9].job_name=api-gateway
scrape_configs[9].metrics_path=/actuator/prometheus
scrape_configs[9].static_configs[0].targets[0]=localhost:8080
