spring.application.name=SkillService

# Server port
server.port=8084

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync-skills

#Config
spring.config.import=optional:configserver:http://localhost:9999/config