# ===============================
# 🟡 EUREKA SERVER
# ===============================
spring.application.name=EurekaServer
server.port=8761

# ❌ Do NOT register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka URL (self)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional (clean dashboard)
eureka.server.enable-self-preservation=true

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.enabled=true
management.zipkin.tracing.connect-timeout=5s
management.zipkin.tracing.read-timeout=10s

# Log file
logging.file.name=logs/app.log

# Log level
logging.level.root=INFO
logging.level.org.springframework=INFO


