spring.application.name=SessionService

# Server port
server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync-sessions

#Config
spring.config.import=optional:configserver:http://localhost:9999/config

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest