networks.elk-network.driver=bridge
services.elasticsearch.container_name=elasticsearch
services.elasticsearch.environment[0]=discovery.type=single-node
services.elasticsearch.environment[1]=xpack.security.enabled=false
services.elasticsearch.environment[2]=ES_JAVA_OPTS=-Xms512m -Xmx512m
services.elasticsearch.image=docker.elastic.co/elasticsearch/elasticsearch:8.12.0
services.elasticsearch.networks[0]=elk-network
services.elasticsearch.ports[0]=9200:9200
services.filebeat.command[0]=filebeat
services.filebeat.command[1]=-e
services.filebeat.command[2]=--strict.perms=false
services.filebeat.container_name=filebeat
services.filebeat.depends_on[0]=elasticsearch
services.filebeat.depends_on[1]=kibana
services.filebeat.image=docker.elastic.co/beats/filebeat:8.12.0
services.filebeat.networks[0]=elk-network
services.filebeat.user=root
services.filebeat.volumes[0]=./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
services.filebeat.volumes[1]=../:/logs:ro
services.grafana.container_name=grafana
services.grafana.depends_on[0]=prometheus
services.grafana.image=grafana/grafana
services.grafana.networks[0]=elk-network
services.grafana.ports[0]=3000:3000
services.kibana.container_name=kibana
services.kibana.depends_on[0]=elasticsearch
services.kibana.image=docker.elastic.co/kibana/kibana:8.12.0
services.kibana.networks[0]=elk-network
services.kibana.ports[0]=5601:5601
services.prometheus.container_name=prometheus
services.prometheus.image=prom/prometheus
services.prometheus.networks[0]=elk-network
services.prometheus.ports[0]=9090:9090
services.prometheus.volumes[0]=./prometheus:/etc/prometheus
services.zipkin.container_name=zipkin
services.zipkin.image=openzipkin/zipkin
services.zipkin.networks[0]=elk-network
services.zipkin.ports[0]=9411:9411
version=3.8
