filebeat.inputs[0].enabled=True
filebeat.inputs[0].paths[0]=/logs/*/logs/*.log
filebeat.inputs[0].type=log
output.elasticsearch.hosts[0]=http://elasticsearch:9200
setup.kibana.host=http://kibana:5601
