spring.application.name=GroupService

# Server port
server.port=8086

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync-groups

#Config
spring.config.import=optional:configserver:http://localhost:9999/config