spring.application.name=notification-service
server.port=8089
spring.rabbitmq.host=localhost
spring.config.import=optional:configserver:http://localhost:9999/config

# ===============================
# 📧 MAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=academyskillsync@gmail.com
spring.mail.password=${MAIL_PASSWORD}
