spring.application.name=learner-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync-learners
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:configserver:http://localhost:9999/config
