global.scrape_interval=5s
scrape_configs[0].job_name=spring-boot-services
scrape_configs[0].metrics_path=/actuator/prometheus
scrape_configs[0].static_configs[0].targets[0]=host.docker.internal:8080
scrape_configs[0].static_configs[0].targets[1]=host.docker.internal:8081
